export abstract class RecipeConstants {
  static readonly storeFeatureKey = 'Clients'
  static readonly notificationTitle = 'Clients'
  static readonly collectionName = 'clients'
}

export enum PLATE_TYPE {
  MAIN = 'MISC.PLATE_TYPE.MAIN',
  ENTRANCE = 'MISC.PLATE_TYPE.ENTRANCE',
  DRINK = 'MISC.PLATE_TYPE.DRINK',
  SALAD = 'MISC.PLATE_TYPE.SALAD',
  RICE = 'MISC.PLATE_TYPE.RICE',
  TOPPING = 'MISC.PLATE_TYPE.TOPPING',
  DESSERT = 'MISC.PLATE_TYPE.DESSERT',
  EXTRA = 'MISC.PLATE_TYPE.EXTRA',
}

export enum PROTEIN_CATEGORY {
  MEAT = 'MISC.PROTEIN_CATEGORY.MEAT',
  CHICKEN = 'MISC.PROTEIN_CATEGORY.CHICKEN',
  FISH = 'MISC.PROTEIN_CATEGORY.FISH',
  VEGI = 'MISC.PROTEIN_CATEGORY.VEGI',
  NO_CATEGORY = 'MISC.PROTEIN_CATEGORY.NO_CATEGORY',
}
